PLOT_NAME = 04_AREA_PLOT
RES = DAC-saxpy-rm-1C1c8w16t-p1 DAC-saxpy-rm-1C1c8w16t-p2 DAC-saxpy-rm-1C1c8w16t
RES += DAC-saxpy-rm-1C1c16w16t-p1 DAC-saxpy-rm-1C1c16w16t-p2 DAC-saxpy-rm-1C1c16w16t
RES += DAC-saxpy-rm-1C1c8w32t-p1 DAC-saxpy-rm-1C1c8w32t-p2 DAC-saxpy-rm-1C1c8w32t
RES += DAC-saxpy-rm-1C1c16w32t-p1 DAC-saxpy-rm-1C1c16w32t-p2 DAC-saxpy-rm-1C1c16w32t
RES = DAC-sfilter-rm-1C1c8w16t-p1 DAC-sfilter-rm-1C1c8w16t-p2 DAC-sfilter-rm-1C1c8w16t
RES += DAC-sfilter-rm-1C1c16w16t-p1 DAC-sfilter-rm-1C1c16w16t-p2 DAC-sfilter-rm-1C1c16w16t
RES += DAC-sfilter-rm-1C1c8w32t-p1 DAC-sfilter-rm-1C1c8w32t-p2 DAC-sfilter-rm-1C1c8w32t
RES += DAC-sfilter-rm-1C1c16w32t-p1 DAC-sfilter-rm-1C1c16w32t-p2 DAC-sfilter-rm-1C1c16w32t
RES += DAC-sgemm-rm-1C1c8w16t-p1 DAC-sgemm-rm-1C1c8w16t-p2 DAC-sgemm-rm-1C1c8w16t
RES += DAC-sgemm-rm-1C1c16w16t-p1 DAC-sgemm-rm-1C1c16w16t-p2 DAC-sgemm-rm-1C1c16w16t
RES += DAC-sgemm-rm-1C1c8w32t-p1 DAC-sgemm-rm-1C1c8w32t-p2 DAC-sgemm-rm-1C1c8w32t
RES += DAC-sgemm-rm-1C1c16w32t-p1 DAC-sgemm-rm-1C1c16w32t-p2 DAC-sgemm-rm-1C1c16w32t
RES += DAC-sgemv-rm-1C1c8w16t-p1 DAC-sgemv-rm-1C1c8w16t-p2 DAC-sgemv-rm-1C1c8w16t
RES += DAC-sgemv-rm-1C1c16w16t-p1 DAC-sgemv-rm-1C1c16w16t-p2 DAC-sgemv-rm-1C1c16w16t
RES += DAC-sgemv-rm-1C1c8w32t-p1 DAC-sgemv-rm-1C1c8w32t-p2 DAC-sgemv-rm-1C1c8w32t
RES += DAC-sgemv-rm-1C1c16w32t-p1 DAC-sgemv-rm-1C1c16w32t-p2 DAC-sgemv-rm-1C1c16w32t

include ../common.mk