PLOT_NAME = Figure_10
RES = ASPLOS-COMP-conv2d-im-1C2c4w8t ASPLOS-COMP-conv2d-im-1C4c8w16t ASPLOS-COMP-conv2d-im-4C4c8w32t
RES += ASPLOS-COMP-knn-im-1C2c4w8t ASPLOS-COMP-knn-im-1C4c8w16t ASPLOS-COMP-knn-im-4C4c8w32t
RES += ASPLOS-COMP-vecadd-im-1C2c4w8t ASPLOS-COMP-vecadd-im-1C4c8w16t ASPLOS-COMP-vecadd-im-4C4c8w32t
RES += ASPLOS-COMP-sgemm-im-1C2c4w8t ASPLOS-COMP-sgemm-im-1C4c8w16t ASPLOS-COMP-sgemm-im-4C4c8w32t
RES += ASPLOS-COMP-sfilter-im-1C2c4w8t ASPLOS-COMP-sfilter-im-1C4c8w16t ASPLOS-COMP-sfilter-im-4C4c8w32t
RES += ASPLOS-COMP-saxpy-im-1C2c4w8t ASPLOS-COMP-saxpy-im-1C4c8w16t ASPLOS-COMP-saxpy-im-4C4c8w32t

include ../common.mk