PLOT_NAME = 00_MOTIVATION
INPUT_DIR ?= ../inputs
NUM_CPUS = 15
RES = DAC-aggr-im-1C1c8w16t DAC-conv2d-im-1C1c8w16t DAC-knn-im-1C1c8w16t 
RES += DAC-saxpy-im-1C1c8w16t DAC-sfilter-im-1C1c8w16t DAC-sgemm-im-1C1c8w16t 
RES += DAC-sgemv-im-1C1c8w16t

include ../common.mk