PLOT_NAME = Figure_13
RES = COMP-conv2d-rm-1C4c8w4t COMP-conv2d-rm-1C4c8w8t COMP-conv2d-rm-1C4c8w16t COMP-conv2d-rm-1C4c8w32t
RES += COMP-knn-rm-1C4c8w4t COMP-knn-rm-1C4c8w8t COMP-knn-rm-1C4c8w16t COMP-knn-rm-1C4c8w32t
RES += COMP-vecadd-rm-1C4c8w4t COMP-vecadd-rm-1C4c8w8t COMP-vecadd-rm-1C4c8w16t COMP-vecadd-rm-1C4c8w32t
RES += COMP-sgemm-rm-1C4c8w4t COMP-sgemm-rm-1C4c8w8t COMP-sgemm-rm-1C4c8w16t COMP-sgemm-rm-1C4c8w32t
RES += COMP-sfilter-rm-1C4c8w4t COMP-sfilter-rm-1C4c8w8t COMP-sfilter-rm-1C4c8w16t COMP-sfilter-rm-1C4c8w32t
RES += COMP-saxpy-rm-1C4c8w4t COMP-saxpy-rm-1C4c8w8t COMP-saxpy-rm-1C4c8w16t COMP-saxpy-rm-1C4c8w32t

include ../common.mk