PLOT_NAME = 02_CORE_SCALABILITY
#INPUT_DIR ?= ./inputs
INPUT_DIR ?= ./dummy_inputs
NUM_CPUS = 15

RES += DAC-saxpy-im-1C1c8w16t-u1 DAC-saxpy-im-1C1c8w16t-u2 DAC-saxpy-im-1C1c8w16t-u4 DAC-saxpy-im-1C1c8w16t-u8
RES += DAC-sgemm-im-1C1c8w16t-u1 DAC-sgemm-im-1C1c8w16t-u2 DAC-sgemm-im-1C1c8w16t-u4 DAC-sgemm-im-1C1c8w16t-u8
RES += DAC-sfilter-im-1C1c8w16t-u1 DAC-sfilter-im-1C1c8w16t-u2 DAC-sfilter-im-1C1c8w16t-u4 DAC-sfilter-im-1C1c8w16t-u8
RES += DAC-sgemv-im-1C1c8w16t-u1 DAC-sgemv-im-1C1c8w16t-u2 DAC-sgemv-im-1C1c8w16t-u4 DAC-sgemv-im-1C1c8w16t-u8

include ../common.mk