PLOT_NAME = Figure_12
#RES = COMP-conv2d-rm-1C4c8w16tp1 COMP-conv2d-rm-1C4c8w16tp2 COMP-conv2d-rm-1C4c8w16tp3
RES += COMP-knn-rm-1C4c8w16tp1 COMP-knn-rm-1C4c8w16tp2 COMP-knn-rm-1C4c8w16tp3
#RES += COMP-vecadd-rm-1C4c8w16tp1 COMP-vecadd-rm-1C4c8w16tp2 COMP-vecadd-rm-1C4c8w16tp3
RES += COMP-sgemm-rm-1C4c8w16tp1 COMP-sgemm-rm-1C4c8w16tp2 COMP-sgemm-rm-1C4c8w16tp3
RES += COMP-sfilter-rm-1C4c8w16tp1 COMP-sfilter-rm-1C4c8w16tp2 COMP-sfilter-rm-1C4c8w16tp3
RES += COMP-saxpy-rm-1C4c8w16tp1 COMP-saxpy-rm-1C4c8w16tp2 COMP-saxpy-rm-1C4c8w16tp3

include ../common.mk