PLOT_NAME = 02_CORE_SCALABILITY
INPUT_DIR ?= ../inputs
NUM_CPUS = 15

RES += DAC-conv2d-im-1C1c8w16t DAC-conv2d-im-1C2c8w16t
RES += DAC-conv2d-im-1C8c8w16t
RES += DAC-knn-im-1C1c8w16t DAC-knn-im-1C2c8w16t
RES += DAC-knn-im-1C8c8w16t DAC-knn-im-1C32c8w16t
RES += DAC-saxpy-im-1C1c8w16t DAC-saxpy-im-1C2c8w16t
RES += DAC-saxpy-im-1C8c8w16t DAC-saxpy-im-1C32c8w16t
RES += DAC-sfilter-im-1C1c8w16t DAC-sfilter-im-1C2c8w16t
RES += DAC-sfilter-im-1C8c8w16t DAC-sfilter-im-1C32c8w16t
RES += DAC-sgemm-im-1C1c8w16t DAC-sgemm-im-1C2c8w16t
RES += DAC-sgemm-im-1C8c8w16t DAC-sgemm-im-1C32c8w16t
RES += DAC-sgemv-im-1C1c8w16t DAC-sgemv-im-1C2c8w16t
RES += DAC-sgemv-im-1C8c8w16t DAC-sgemv-im-1C32c8w16t

include ../common.mk
