PLOT_NAME = 02_INTERCORE
INPUT_DIR ?= ../inputs
NUM_CPUS = 15
# kernels: conv2d, knn, saxpy, sfilter, sgemm, sgemv
RES =  DAC-conv2d-rm-1C1c8w16t DAC-conv2d-rm-1C1c8w32t 
RES += DAC-conv2d-rm-1C1c16w16t DAC-conv2d-rm-1C1c16w32t
RES += DAC-knn-rm-1C1c8w16t DAC-knn-rm-1C1c8w32t
RES += DAC-knn-rm-1C1c16w16t DAC-knn-rm-1C1c16w32t
RES += DAC-saxpy-rm-1C1c8w16t DAC-saxpy-rm-1C1c8w32t
RES += DAC-saxpy-rm-1C1c16w16t DAC-saxpy-rm-1C1c16w32t
RES += DAC-sfilter-rm-1C1c8w16t DAC-sfilter-rm-1C1c8w32t
RES += DAC-sfilter-rm-1C1c16w16t DAC-sfilter-rm-1C1c16w32t
RES += DAC-sgemm-rm-1C1c8w16t DAC-sgemm-rm-1C1c8w32t
RES += DAC-sgemm-rm-1C1c16w16t DAC-sgemm-rm-1C1c16w32t
RES += DAC-sgemv-rm-1C1c8w16t DAC-sgemv-rm-1C1c8w32t
RES += DAC-sgemv-rm-1C1c16w16t DAC-sgemv-rm-1C1c16w32t

include ../common.mk
