PLOT_NAME = Figure_14

RES = COMP-conv2d-rm-1C4c8w16t COMP-conv2d-rm-2C4c8w16t COMP-conv2d-rm-4C4c8w16t COMP-conv2d-rm-8C4c8w16t
RES += COMP-knn-rm-1C4c8w16t COMP-knn-rm-2C4c8w16t COMP-knn-rm-4C4c8w16t COMP-knn-rm-8C4c8w16t
RES += COMP-vecadd-rm-1C4c8w16t COMP-vecadd-rm-2C4c8w16t COMP-vecadd-rm-4C4c8w16t COMP-vecadd-rm-8C4c8w16t
RES += COMP-sgemm-rm-1C4c8w16t COMP-sgemm-rm-2C4c8w8t COMP-sgemm-rm-4C4c8w8t COMP-sgemm-rm-8C4c8w8t
RES += COMP-sfilter-rm-1C4c8w16t COMP-sfilter-rm-2C4c8w16t COMP-sfilter-rm-4C4c8w16t COMP-sfilter-rm-8C4c8w16t
RES += COMP-saxpy-rm-1C4c8w16t COMP-saxpy-rm-2C4c8w16t COMP-saxpy-rm-4C4c8w16t COMP-saxpy-rm-8C4c8w16t

include ../common.mk