PLOT_NAME = 02_CORE_SCALABILITY
INPUT_DIR ?= ../inputs
NUM_CPUS = 15

RES += DAC-saxpy-rm-1C1c8w16t DAC-saxpy-rm-1C2c8w16t
RES += DAC-saxpy-rm-1C4c8w16t DAC-saxpy-rm-1C8c8w16t
RES += DAC-sgemm-rm-1C1c8w16t DAC-sgemm-rm-1C2c8w16t
RES += DAC-sgemm-rm-1C4c8w16t DAC-sgemm-rm-1C8c8w16t
RES += DAC-sfilter-rm-1C1c8w16t DAC-sfilter-rm-1C2c8w16t
RES += DAC-sfilter-rm-1C4c8w16t DAC-sfilter-rm-1C8c8w16t
RES += DAC-sgemv-rm-1C1c8w16t DAC-sgemv-rm-1C2c8w16t
RES += DAC-sgemv-rm-1C4c8w16t DAC-sgemv-rm-1C8c8w16t

include ../common.mk